// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoveIt.Data;

#nullable disable

namespace MoveIt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MoveIt.Models.Carrier.Offer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CarrierId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportHour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCarrierConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCustomerConfirmed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("MoveIt.Models.Customer.Ad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromWhere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsDepth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsLength")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsVolume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsWeight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoodsWidth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToWhere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportHour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("MoveIt.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCarrier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
